### ISSUE TITLE
[hooks] useState - "setState" callback

### ISSUE THREAD

**Issue by marcellomontemagno** [reactjs/rfcs#98] opened 2018-12-19 15:52 UTC
Hi, I'm very hyped about the hooks api and I started experimenting with it on some small side project.

I've noticed that the "setState" function returned by the `useState` hook doesn't have an "afterRender" callback (the second argument of `this.setState` in classes)

I didn't find further informations about this in the doc. Is there any design reason why the "afterRender" callback is not present? Is there a plan to introduce it later on?

The reason I ask is that during the past years of react usage I found a few scenarios (very rarely though) were not having the "afterRender" callback would result in a quite tedious implementation of `componentDidUpdate` or pushed me to change the shape of my state to work around it (I can provide examples about this)

In the meanwhile here the snippet I used to understand that no "afterRender" callback is used by the "setState" of hooks

Counter.js
```
import React, {useState} from 'react';

export const defaultState = {count: 0}

export const useCounter = () => {

  const [state, setState] = useState(defaultState)

  return {
    ...state,
    onIncreaseCounter () {
      setState({...state, count: state.count + 1}, () => {console.log('++++++++++++++++++')})
    },
    onDecreaseCounter () {
      setState({...state, count: state.count - 1}, () => {console.log('++++++++++++++++++')})
    }
  }

}

export default function Counter ({count, onIncreaseCounter, onDecreaseCounter}) {
  return <div>
    {count}
    <button onClick={onIncreaseCounter}>+</button>
    <button onClick={onDecreaseCounter}>-</button>
  </div>
}
```

Root.js
```
import React from 'react';

import Counter, {useCounter} from "./Counter";

export default function Root () {
  return <Counter {...useCounter()}/>
}
```

the log never appears in the console after after increasing and decreasing the counter

**Comment by sandiiarov** [comment] 2018-12-19 16:09
Try:
```js
  setState({ ...state, count: state.count - 1 }, console.log('++++++++++++++++++'))
```

**Comment by jquense** [comment] 2018-12-19 16:34
@sandiiarov that won't do what @marcellomontemagno is asking, it just logs immediately, not in the callback.

@marcellomontemagno you can use a `useEffect` hook to do 'after render' callbacks and coordinate with the current state value

**Comment by gustavo-depaula** [comment] 2019-01-07 00:02
Yes, [there is not a second argument on the setState hook callback](https://reactjs.org/docs/hooks-reference.html#usestate). +1'd because I also want to know the reason why.

**Comment by renatoagds** [comment] 2019-01-07 01:08
@marcellomontemagno agree with @jquense to use `useEffect`, since `setState` will cause a re-render and it will call `useEffect`. Other point is remember that `setState` callback isn't guarantee that state changed.

**Comment by MohamedLamineAllal** [comment] 2019-04-02 19:22
Same here, i find the callback very useful. Too i can't imaging a scenario why this should be removed. Or how it influence performance. Except maybe for a better unit testing. I really want to know the why !

**Comment by phryneas** [comment] 2019-04-02 20:33
Because it invokes a thought pattern that may very well be an antipattern with hooks.

With hooks, you are writing code more declarative than imparative. 

The thought of "do one thing THEN do another thing THEN do another thing" would be the imparative (here: callback- or promise-based) way.

What actually should be done in the hooks model would rather be a "if this has been rendered, and this property is different than before, X should be done to reach the target state", which is more declarative. You don't designate when stuff happens, but just give a condition/dependency and let react pick the right point in time for it.

**Comment by jamesplease** [comment] 2019-04-03 05:44
The warning that's logged when trying to use the 2nd callback argument provides a hint as to why it isn't supported:

![image](https://user-images.githubusercontent.com/2322305/55455342-1eb3ca80-5598-11e9-9d41-5da4cd34198c.png)

Judging from the message, it seems that using `useEffect` is preferred instead, which is an alternative @jquense mentioned [above](https://github.com/reactjs/rfcs/issues/98#issuecomment-448659736) .

Here's a CodeSandbox example of the `Counter` from the initial post using `useEffect`: [CodeSandbox link](https://codesandbox.io/s/48ynxxq7zx)

You may already know all of this @marcellomontemagno but since hooks are new-ish I figured I'd post this just in case! 😅

**Comment by alexfedoseev** [comment] 2019-04-13 02:01
> What actually should be done in the hooks model would rather be a "if this has been rendered, and this property is different than before, X should be done to reach the target state", which is more declarative. You don't designate when stuff happens, but just give a condition/dependency and let react pick the right point in time for it.

This reminds me of a game "guess what to do in componentWillReceiveProps by comparing N different things".

---

I have a form library and I'm thinking of how to update it to the new API. I'm just getting myself familiar with hooks and got stuck pretty soon on the following case: user submits a form.

In the previous class-based model, when `Submit` action is dispatched, [I update a state and trigger `onSubmit` effect](https://github.com/alexfedoseev/re-formality/blob/master/src/Formality__Form.re#L230-L255), using `setState` callback (`UpdateWithSideEffects` callback in Reason). Simple as that.

In the hooks world I can't do that. I have a reducer that returns a state only and `useEffect` that runs (or not) on each re-render independently. Schedule of `useEffect` can be managed by specifying array of deps and if one of the deps has changed, effect is triggered. So, if I understand docs correctly, I need to:
1. find a value in state that is changed on `Submit` and pass it to deps array: this is a form status
2. inside effect, check if current value of form status is `Submitting` then trigger `onSubmit` handler

Here's the first confusing point: what if re-render was triggered during submission for some unrelated reason (e.g. parent props was updated due to whatever). In fact, submission request was triggered and is ongoing but since re-render was triggered and form status is still `Submitting` -> all conditions are met to re-run effect.

This common case seems pretty tricky with hooks. But hopefully I just didn't grok it yet and there is clean way to handle it within new model.

**Comment by phryneas** [comment] 2019-04-13 08:54
Usually, I'd trigger the asynchronous side-effect directly from button.onClick or form.onSubmit and store the results back using a useReducer dispatch. Since that seems not to be an option for you, maybe do something along these lines?

### depend only on isSubmitting, pass state via Ref

```
const [state, dispatch] = useReducer(...);
const stateRef = useRef();
stateRef.current = state;

useEffect(() => {
  if (!state.isSubmitting) { return; }
  // do your submitting with stateRef.current in here
  // then dispatch the results
}, [state. isSubmitting]);
```

The effect only triggers when state.isSubmitting changes and within it, you have access to the latest state using the ref. Though I would not recommend using this reference hack in every situation, in your case it seems fitting.

### depend on full state, keep track of last submit in a Ref

in this case, we assume a property `state.submitCount` that is increased by 1 with every submit

```
const [state, dispatch] = useReducer(...);
const lastSubmittedRef = useRef(0);

useEffect(() => {
  if (lastSubmittedRef.current === state.submitCount) { return; }
  lastSubmittedRef.current = state.submitCount;
  // handling here
}, [state]);

```

**Comment by alexfedoseev** [comment] 2019-04-13 09:07
I spent some time today on this and ended up with using custom hook that brings back `UpdateWithSideEffects` to hooks with almost zero changes to initial reducer: https://github.com/alexfedoseev/re-formality/pull/51/files#diff-376207e44be3824884705dd487fd098c

Looks like it works. All props to @bloodyowl for initial gist: https://gist.github.com/bloodyowl/64861aaf1f53cfe0eb340c3ea2250b47

**Comment by rwieruch** [comment] 2019-05-31 11:24
Yes, you can use useEffect/useLayoutEffect to add your custom callback function after updating state. If you are looking for an out of the box solution, maybe [this custom hook](https://github.com/the-road-to-learn-react/use-state-with-callback) which is nothing else than useState with a callback function may be handy for you.

**Comment by slorber** [comment] 2019-06-11 18:03
@rwieruch your code is dangerous, everytime the callback changes (which does happen frequently if using closures) the callback will fire again. You need to "stabilize" your callbacks using refs (Dan Abramov has a nice blog post somewhere on that topic)

**Comment by kdzhambazov** [comment] 2019-06-20 13:37
I understand that from a general case point of view useEffect() will run our cone on the place of the old setState() callback, however consider this case:

...
onChange() {
...
          this.setState(stateToSet, () => {
                if (this.props.parentOnChange) {
                    this.props.parentOnChange(this.state);
                }
            });
....
}

onBlur() {
...
          this.setState(stateToSet, () => {
                if (this.props.parentOnBlur) {
                    this.props.parentOnBlur(this.state);
                }
            });
....
}

So here we want to execute 2 different callbacks depending on the event. If we fire onChnage we want to fire its parent onChange if provided in the component props and so on. In short every type of set state need to have a separate useEffect(). How can this be managed with hooks without the "removed" callback. The only way I could think of is to have additional if / else logic inside the useEffect() hook ?

**Comment by phryneas** [comment] 2019-06-20 16:09
Exactly that example is why you wouldn't want that callback. 
In your case, usually you want to directly call `props.parentOnChange` after calling setState, without waiting for setState to acutally happen. (so you wouldn't use useEffect as well!)
The reasoning for that is pretty simple: if `props.parentOnChange` also triggers a state change, those two will be batched together . But if you wait until after the first setState has completed, you might introduce a double-render and inbetween have inconsistent states.
Also, I can't think of many situations where you really would want to wait for setState to propagate before calling that parent callback - the parent has no access to the internal state of the child component anyways, so there'd be no way the child state is of any interest to the parent component.

**Comment by rwieruch** [comment] 2019-06-22 12:23
> Also, I can't think of many situations where you really would want to wait for setState to propagate before calling that parent callback ...

In my case, I wanted to wait for the re-render, because afterward I can operate on a `ref` which would be hidden before due a conditional rendering. For instance, I have a boolean state which either shows a list or an item to edit. If I am in the latter state, I want to save the edited item and return to the list of items. As soon as the re-render completes, and all list items with their refs are available, I can scroll programmatically to the updated item which has been edited.

**Comment by eslachance** [comment] 2019-06-28 03:21
The need for a way to "chain" setState is one that I find myself having to deal with. Consider the following code: https://text.evie.codes/igacuvadug.js . Here, my issue is that I need to do this on clicking my component : 

- set the Spring reset to true
- after it's set to true, reset my percentage to 0, so it's "instantaneous" and not animated
- Once that's done, increment my count, then set the Spring reset to false, and then set my component to no longer be clickable.

With the lack of callback (which, to be fair, I'd immediately turn into a promise and use async/await, because c'mon, callback hell!), I find myself unable to chain these in any meaninful fashion. Since those operations become batched, it means my progress bar's position resets to zero without the Spring reset being triggered, so it doesn't just go to 0, it *moves* to 0.

The suggestions above (and what I've seen previously in terms of useEffect solutions) account for replacing *one* callback but I need to replace 4 of them (I could batch some of these things, but not all of them). The useEffect condition hell I would put myself in sounds like it would be a nightmare to manage.

**Comment by phryneas** [comment] 2019-06-28 07:28
@eslachance here's a working example without useEffect at all: https://codesandbox.io/s/weathered-tdd-794hs

Here's what I did:
* useReducer instead of five calls to state setters so all state is set in one atomic action
* keep track of last progress - reset is true when `lastProgress > progress`, no need to track any "reset" thing itself.
* reset belongs on Spring, not on ProgressWrapper

**Comment by eslachance** [comment] 2019-06-28 20:38
Damn that's why my reset wasn't working 😅
Thank you @phryneas , that's going above and beyond to provide a working example. I will hold on to it preciously. You're awesome!

**Comment by slorber** [comment] 2019-07-01 14:11
Hey all

This is how I solve it in my apps. Just published it as an opensource package:

https://github.com/slorber/use-async-setState

```ts
import { useAsyncSetState, useGetState } from "use-async-setState";

const Comp = () => {
  const [state,setStateAsync] = useAsyncSetState({ counter: 0 });
  const getState = useGetState(state);
  
  const incrementTwiceAndSubmit = async () => {
    await setStateAsync({...getState(): counter: getState().counter + 1});
    await setStateAsync({...getState(): counter: getState().counter + 1});
    await submitState(getState());
  }
  
  return <div>...</div> 
}   
```

**Comment by arjun-menon** [comment] 2019-07-27 08:39
Great thread! I was wondering about the same thing.

**Comment by yairEO** [comment] 2019-08-26 13:54
There's a very good discussion on Stackoverflow:
[Equivalent to componentDidUpdate using React hooks](https://stackoverflow.com/q/53255951/104380)

**Comment by rwieruch** [comment] 2019-08-27 00:35
> There's a very good discussion on Stackoverflow:
> [Equivalent to componentDidUpdate using React hooks](https://stackoverflow.com/q/53255951/104380)
> 
> The `useEffect` method for tracking `useState` updates is (in some cases) undesirable, since it is invoked immediately on mount, regardless of a state change.
> 
> My scenario is that I have some `onChnage` callback prop passed to my component which, which *_must_ only be fired when a change was actually made, because it triggers a heavy server request.

Do you want to open a PR for https://github.com/the-road-to-learn-react/use-state-with-callback to include the prevention of calling the callback on mount? Didn't think about it for my use case back then, but I think it should be only something along these lines:

```
const isMounted = React.useRef(false);

React.useEffect(() => {
  if (isMounted.current) {
    return;
  }

  // do callback

  isMounted.current = true;
});
```

**Comment by iremlaya** [comment] 2019-08-30 21:56
+1

**Comment by sag1v** [comment] 2019-10-02 06:53
There is another scenario which one might want a to run a callback per state update, i think its the same or similar to what was mentioned in [this comment](https://github.com/reactjs/rfcs/issues/98#issuecomment-504029077) by @kdzhambazov .

If you want to run 2 *different* callbacks for the same data that was changed, you can't do that only with `useEffect`. This will require some extra logic, maybe tracking a callback queue, some state to determine if this is the first render and if an update was triggered but the state didn't really changed because the next value is the same as previous (in classes the callback will trigger even if the state wasn't really updated). 

This can be a custom hook obviously:
```
function useStateWithCallback(initialValue) {
  const [state, setState] = useState(initialValue);

  // we need this flag for 2 reasons:
  // 1. To prevent the call on mount (first useEffect call)
  // 2. To force the effect to run when the state wasn't really updated
  // i.e next-state === previous-state.
  const [shouldRunCBs, setRunCBs] = useState(false);

  // tracking a queue because we may have more than 1 callback per update?
  const cbQRef = useRef([]);

  function customSetState(value, cb) {
    if (typeof cb === "function") {
      cbQRef.current.push(cb);
      // we force the effect to run even if the state wasn't really updated
      // i.e next-state === previous-state.
      // this is how the callback in classes work as well
      // we can opt-out from this behaviour though
      setRunCBs(true);
    }
    setState(value);
  }

  useEffect(() => {
    if (shouldRunCBs) {
      // we must pass back the new value
      //because the consumers can't get it via the closure of thier component
      // and they don't have an instance like in classes.
      cbQRef.current.forEach(cb => cb(state));
      cbQRef.current = [];
      setRunCBs(false);
    }
  }, [state, shouldRunCBs]);

  return [state, useCallback(customSetState, [])];
}
```

Here is [a sandbox ](https://codesandbox.io/s/setstate-callback-dpmsg)with a simple use case

**Comment by Jessidhia** [comment] 2019-10-02 07:08
That _almost_ works -- if using synchronous React (`ReactDOM.render`) and the state change comes from outside React (e.g. something that runs after an `await`, or other non-React events), you will get the callback invoked with the old value, not the new one, because React will update immediately with `setRunCBs(true)`, the `Effect` will be prepared, and it will be invoked when you try to call `setState(value)`. Then when the new `value` is entered it won't have callbacks to call anymore.

---

This very specific nitpicking aside (which you can't reproduce in your sandbox as you're using React events), this pattern still looks really strange. If you want to guarantee a `setState` **always** causes an update, then set it to an object, as objects will never be `Object.is` another object. Use one Effect for each side effect you want to trigger. Use a Ref to conditionally enable the effect before dispatching if you want it to be very specific to where you're dispatching from.

**Comment by sag1v** [comment] 2019-10-02 07:56
@Jessidhia Thanks for the input, can you create a sandbox with your async example and my hook showing the bug?

**Comment by chenyanfei-m** [comment] 2019-11-21 03:10
I use it like this:
```
import React, { useState, useRef, useEffect } from 'react'

export default function useStateWithCallback(initState) {
    const callbackRef = useRef(null)

    const [state, setState] = useState(initState)

    useEffect(() => {
        if (callbackRef.current) {
            callbackRef.current(state)
            callbackRef.current = null
        }
    }, [state])

    const setCallbackState = (value, callback) => {
        callbackRef.current = typeof callback === 'function' ? callback : null
        setState(value)
    }

    return [state, setCallbackState]
}
```
```
const [index, setIndex] = useStateWithCallback(0)
setIndex(1, () => console.log('callback'))
```

**Comment by slorber** [comment] 2019-11-21 15:05
Most solutions here using a single callback ref won't work if multiple consecutive setState calls are performed. Also, why do you really prefer a function callback compared to a promise, isn't it simpler to deal with promises to build complex flows?

Take another look at https://github.com/slorber/use-async-setState please

![image](https://user-images.githubusercontent.com/749374/69349799-b295ec00-0c78-11ea-85df-96d814a9c803.png)

**Comment by slorber** [comment] 2019-11-21 15:15
@sag1v your solution is probably the closest to mine except doing setState(1,cb) if state=1 will lead to an extra unnecessary re-render. Just look how I handled this more efficiently here: https://github.com/slorber/use-async-setState/blob/master/src/index.ts#L33

**Comment by sag1v** [comment] 2019-11-21 23:22
@slorber Thanks. It was just a naive implementation example. My point was to show there are use cases for a state update callback, it is doable in user-land but maybe it should be provided by the library as it was with classes.

**Comment by arkakkar** [comment] 2020-04-08 07:27
useEffect is the proper solution to consume the updated state, but useEffect is called everytime the state is updated, so I wouldn't want to call my setState callback everytime. Can return a promise instead and user the thenable callback on-demand.
Here is a simple solution to the problem:

```
updateState({...newState}).catch(err => logger.log(err)).then(updatedState => {
      //do whatever you want with updated state
})

const promiseRef = useRef({});
updateState = (newState) => {
    promiseRef.current.promise = new Promise((resolve, reject) => {
          promiseRef.current.isPending = true;
          promiseRef.current.resolve = resolve;

          /** update state here through **useState** or **useReducer dispatch** with newState */
    });
    
    return promiseRef.current.promise;
}

/** deep object comparison of state */
useEffect(() => {
        let {promise, isPending, resolve} = promiseRef.current;
        if (promise && isPending && typeof resolve == 'function') {
            promiseRef.current.isPending = false;
            promiseRef.current.resolve(state);
            promiseRef.current.resolve = null;
        }
},[state]);

```

**Comment by slorber** [comment] 2020-04-08 11:13
@arkakkar this is what I do with https://github.com/slorber/use-async-setState + handle case like await setState(s => s) which does not trigger useEffect + handle rejects etc

**Comment by adamkleingit** [comment] 2020-04-13 16:53
> > Also, I can't think of many situations where you really would want to wait for setState to propagate before calling that parent callback ...
> 
> In my case, I wanted to wait for the re-render, because afterward I can operate on a `ref` which would be hidden before due a conditional rendering. For instance, I have a boolean state which either shows a list or an item to edit. If I am in the latter state, I want to save the edited item and return to the list of items. As soon as the re-render completes, and all list items with their refs are available, I can scroll programmatically to the updated item which has been edited.

Then you should have a useEffect on the boolean flag and scroll to the list if it changes. Something like:
```
useEffect(() => {
  if (!isEditing) {
    listRef.current.scrollTo();
  }
}, [isEditing]);
```
Because useEffect runs after rendering, the ref will be available

**Comment by Genarito** [comment] 2020-04-22 22:38
I don't understand why people are reluctant to add a second parameter to `setState` (or other Hook). Hooks were made to make React simpler... But instead of writting:

```
this.setState({ loading: true}, () => {
    fetch('...').then(() => this.setState({loading: false}))
    .catch(() => this.setState({loading: false}))
})
```

Which is much more clearer and compact you propose to make a `useEffect` which checks if the state has changed to set a simple flag. I have a lot of requests with their own flags, and instead of making things simpler the proposal is write 423K of `useEffect` functions in the same file to handle every one.
This is a very requested feature, in fact, most of the custom Hook lists you can find on Github include a Hook with callback

**Comment by marcellomontemagno** [comment] 2020-05-16 11:43
I think I'm happy with this reply https://github.com/reactjs/rfcs/issues/98#issuecomment-479188615

This is still something people will have to deal with so here my recipe to deal with the lack of `setState` callback:

### Option 1: subscribe to the state change you made via useCallback

This option might not be suitable for you if that very same state change can happen for many different reasons.

### Options 2: in the event callback where the first setState is happening, just invoke another setState right after the first one

This works because, even though the first `setState` is indeed asynchronous, the order of the 2 `setState` is still guaranteed.

Option 2 might not be suitable for you if instead of invoking a second `setState` you need to invoke an imperative function of the browser such as `inputRef.focus()` as the browser will not wait for the first `setState` to be applied to the DOM.

If you need to invoke an imperative API from the browser such as `inputRef.focus()` and option 1 is not suitable for your use case you have the following 2 options available:

### Option 2.1: Hide the imperative API from the browser making react your only source of truth.

Here an example of how to try to convert an imperative API from the browser in something  react can control:

```
import React, {useRef, useEffect, useState} from 'react'

const EnhancedInput = ({focus, onFocus, onBlur, ...rest}) => {

  const inputRef = useRef(false)

  useEffect(() => {
    focus && inputRef.current.focus()
  }, [focus])

  return <input
    ref={inputRef}
    onBlur={onBlur}
    onFocus={onFocus}
    {...rest}
  />

}


const ExampleUsage = () => {

  const [hasFocus, setHasFocus] = useState(false)

  return <EnhancedInput focus={hasFocus} onFocus={() => setHasFocus(true)} onBlur={() => setHasFocus(false)}/>

}
```

It might be desirable to have `React` as the single source of truth within your app and after doing so you can then fall back on option 2 invoking `setHasFocus` right after your first `setState`.

### Options 2.2: reintroduce the setState callback by yourself.

@slorber did a good job in making this something reusable via https://github.com/slorber/use-async-setState.

--------

To wrap this up, my personal opinion is that is good to think about `option 1` first but `option 2` might be desirable more often.

Please feel free to follow up with any concern about this recipe or just leave a 👍 If you agree.

I would be happy to formalize this better and add a FAQ to the react documentation about hooks at some point as this discussion had quite a lot of replies.

**Comment by gaearon** [comment] 2021-08-24 19:51
Hi, thanks for your suggestion. RFCs should be submitted as pull requests, not issues. I will close this issue but feel free to resubmit in the PR format.

**Closed by gaearon** 2021-08-24 19:51 UTC
